### ISSUE TITLE
Submtting new admin/report templates with no file attachment returns error.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#101]
Submitting to the upload "admin" and "report" templates menu without actually attaching a file causes an error in the UI. A POST with nothing attached should just ignore the submission.

WebUI Error:
Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.

Shell 500 error:
[19/Jan/2015 09:23:03] "POST /admin/templates/add HTTP/1.1" 500 101 0.0071

**Comment by BuffaloWill** [comment]
thanks @nanotechz9l . just pushed a fix, should ignore the submission now.
