### ISSUE TITLE
Burp import plugin error

### ISSUE THREAD

**Issue by derrabe** [MooseDojo/Serpico#103]
Error displayed : undefined method `+' for nil:NilClass
From line 61 of helpers/vuln_importer.rb.

It appears if exists.notes is nil it throws this error. Workaround:

    if exists.notes
      exists.notes=exists.notes+"<paragraph></paragraph><paragraph></paragraph>#{single.notes}"
    end

**Comment by BuffaloWill** [comment]
thanks @derrabe! Pushed into master.
