### ISSUE TITLE
Template editing with open source software (LibreOffice / OpenOffice)

### ISSUE THREAD

**Issue by mark-orion** [MooseDojo/Serpico#105]
This is a great project - thanks a lot ! It would be great if it was possible to edit the templates with open source software rather than MS Word. I tried editing templates with LibreOffice but always get exceptions for different reasons.

**Comment by BuffaloWill** [comment]
thanks @mark-orion! 

This is likely something we will need to troubleshoot on a case by case basis. I would probably start with a Serpico template written from scratch in LibreOffice. That is, all of the templates were written from Office and inherit MSOffice docx design/functionality. I think starting out with a LibreOffice based document will limit complexity in trying to figure out what's broken. Haven't tested it, but copying text from the office document to an intermediary (e.g. gedit) and then over to LibreOffice would get the basics in.
