### ISSUE TITLE
Role based access control would be a nice feature.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#108]
This would entail giving users access to specific reports only.

**Comment by BuffaloWill** [comment]
Giving a user access to a specific report can be done through the UI. Go to the reports list and click on the silouhette image (e.g. /admin/add_user/[REPORT_ID]). You can assign a "Collaborator" with access to only that report. An admin can also make two non-admin users collaborators on a report.

I will also add this info to the wiki.

**Comment by BuffaloWill** [comment]
Added https://github.com/MooseDojo/Serpico/wiki/Adding-Other-Users-To-A-Report

**Comment by nanotechz9l** [comment]
Thanks.
