### ISSUE TITLE
Having the ability to email reports from UI to requester would be ideal.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#110]
After clicking the "Generate Report" button it would be nice if we had the ability to email the report to the customer/requester straight from the UI (mail server config option, etc).

**Comment by BuffaloWill** [comment]
@nanotechz9l thanks for the feature suggestion. Have to think on this one a bit. Trying to avoid adding any gems for now.

This could be done via scripting; check out the new wiki page which has info on [Automating Serpico] (https://github.com/MooseDojo/Serpico/wiki/Automating-Serpico)

**Comment by BuffaloWill** [comment]
Thank you, we've decided not to implement. This can be done via scripting.
