### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by toonswyzen** [MooseDojo/Serpico#112]
Is it possible to list findings by category ?
I mean list all findings of type Network Security, Social Engineering etc..

**Comment by BuffaloWill** [comment]
hi @toonswyzen. You should be able to get a list of all findings by category in the "Findings Database". Is that what you are looking for?
I added an IRC channel on Freenode if you want do drop in. Might be easier to get help in real time; [#therealserpico](http://webchat.freenode.net/?channels=%23therealserpico&uio=d4)

**Comment by toonswyzen** [comment]
I mean in the template, not int he tool itself :)

**Comment by BuffaloWill** [comment]
Ah good question. You can but it would involve a nesting of conditionals. In pseudo code it would be like:
```
For each finding with risk < 4, risk > 2
If type == "Network Security"
  finding
end if
if type == "Social Engineering"
  finding
end if
...
```

the following is untested in the meta language:
```
¬report/findings_list/findings:::risk<4:::risk>2¬
† type == "Social Engineering" †
  finding
¥
∆
```

**Comment by BuffaloWill** [comment]
Ended up pushing a fix for the string comparison. The following should work after pulling the newest code:
```
† translate(type,$up,$low)=translate('database',$up,$low) †
  finding
¥
```
