### ISSUE TITLE
Add to the Findings Database not working

### ISSUE THREAD

**Issue by muk302** [MooseDojo/Serpico#115]
If I create a new finding, then hit the "add to the findings database", nothing gets added.

My understanding of this functionality is if I create a new finding and expect to see the same in the future, I can just add it from the list of findings in new reports. Am I right?

**Comment by Petessss** [comment]
After creating the new finding did you mark it as approved? If not, you'll have to mark it as approved before it will show up in the findings_add screen.

**Comment by BuffaloWill** [comment]
Going to close the issue. Cheers!

**Comment by muk302** [comment]
Where do I approve from?

**Comment by BuffaloWill** [comment]
@muk302, if you edit the finding from the template database it should have an "Approve" check box. When viewing the list of findings from the Template Database the finding should also be highlighted in red to show that it is currently unapproved. 

The use case is that any user can add a finding to the Template Database, but a finding can not be seen by other users until it is approved by an administrator.

**Comment by muk302** [comment]
I don't see an 'approve' checkbox while editing my new finding. I'm an
admin, but maybe it's still a permission issue on my end.

**Comment by BuffaloWill** [comment]
Make sure you are in the "Findings Database" (the link should be in the top bar of the UI). On the left side you should see a red box that says "Warning you are editing the Template Database". These are the findings that all other users have access to. If you click on edit for one of these findings, there should be an option to Approve it. All admin level users have access to the "Findings Database".
