### ISSUE TITLE
Sorting issues list in Generic Risk Rating

### ISSUE THREAD

**Issue by anantshri** [MooseDojo/Serpico#118]
If i have a high risk entry for XSS (listed as Cross Site Scripting) and SQLi i might want SQLi to be on top and not XSS. we don't have option right now.

**Comment by BuffaloWill** [comment]
Hey @anantshri. Two ways come to mind to do this in the report template:

1. You can use DREAD scoring and still have Serpico generate a Generic Risk Rating report.
  1. Modify config.json to use DREAD
  2. Update your DREAD scores to match Generic Risk (e.g. DREAD > 40 for high, etc)
  3. Within your report template use the DREAD score to sort the findings but then just print a Generic Risk in the text of the finding itself. For example, you would use a "if DREAD > 40" conditional but ignore the DREAD scores and just print "Critical" for the Finding Risk.

2. Use the Generic Risk in your template but perform a string comparison to provide priority for certain findings. For example, "if risk > 3" followed by a second "if title = 'SQL Injection'". (Untested) I believe the meta language line would look like:
```
¬report/findings_list/findings:::translate(title,$up,$low)=translate('SQL Injection',$up,$low)¬
```

**Comment by anantshri** [comment]
I will try that. But just one check so when i mark if DREAD > 40 or any number i would assume the output would automatically be sorted in Descending order of DREAD Scope.

**Comment by BuffaloWill** [comment]
Yes, it should be in descending order. I would check out the dread report template to verify the syntax.
