### ISSUE TITLE
String comparison

### ISSUE THREAD

**Issue by BobPeterson** [MooseDojo/Serpico#120]
Hello, 

First of all, thank you for your awesome work. It works very well. However, I have an issue trying to realize a string comparison. 

My template is as following: 

```
¬report/findings_list/findings:::risk¬
† translate(impact,$up,$low)=translate(’Critical’,$up,$low) †
Test Critical
¥
```

impact is defined in master.rb as a string in TemplateFindings and Findings classes:
```
property :impact, String, :required => false
```

I have an internal error when I generate the report. 
```
xsl:if : could not compile test expression ' translate(impact,$up,$low)=translate(’critical’,$up,$low) '
```
I tried to compare 2 strings using different syntax but it allways fails. 

Example:
      - impact='critical'
      - impact=='critcal'
      - ...

If you have any idea or if you can explain little more about string comparaison it will be cool. Thank you very much.

**Comment by BuffaloWill** [comment]
Thanks @BobPeterson. XSLT uses a single '=' for comparison so your code looks correct. It looks like there is an apostrophe (`) being placed in the string comparison. I would retest with " or ' copied from elsewhere (e.g. notepad). 

Given that string comparison is a rather common test, it makes sense to have a string comparison method in the metalanguage. For example:
```
† string_compare(impact,"Critical") †
```
I will add an issue for this.

**Comment by BobPeterson** [comment]
I have made some tests today. 

You were right about the single quote, I use one copied from notepad and it works (no more error), however the test always failed. 
I didn't understand why until I saw the xslt file generated. 

My risk type was as following (you can notice the first letter in uppercase): 
```
["Low", "Moderate", "High", "Critical"] 
```
The string comparison on your template will be as following: 
```
risk='Critical'
```
So you could think that Critical=Critical so the condition will be true. But when you can see on the xslt file that the second string is in lowercase: 
```
<xsl:if test=" risk = &quot;critical&quot; ">
```
And the following line will confirm that on "./helpers/xslt_generation.rb"
```
omega.downcase
```
Is there a reason to realize a downcase before to add it to the xslt file ? If not it could be interesting to remove it, if this is a bug fix, I will find another way to realize the string comparison. 

Thank you anyway, it's a great work.

**Comment by BuffaloWill** [comment]
The translate function we apply in the xslt:
```
† translate(impact,$up,$low)=translate(’Critical’,$up,$low) †
```
should be setting the case values the same for both ($up=ABCDE.., $low=abcde...). 

Which scoring method (i.e. risk, DREAD, CVSS) are you using? I ask because in the default model there is no "impact" attribute as used in the original issue, only "cvss_impact" which should be a float. If you are using "risk" as your operator then you should do an integer comparison (i.e. risk > 3). 

Thanks again for the detailed effort on the issue.
