### ISSUE TITLE
user defined variables displays escape character

### ISSUE THREAD

**Issue by ccammilleri** [MooseDojo/Serpico#48]
if you add a user defined variable with variable data containing a backslash (including newline) it will display the escaped characters within their form on the user_defined_variables page. This will also cause an escape of death by escaping the additional backslashes upon adding another user defined variable or post.

to recreate:
add variable name: test1234
add variable data: test1234\test1234 (or hit enter between words)
save
view additional backslash characters in variable data

**Comment by BuffaloWill** [comment]
Good call, thanks for the write-up. Looking at a fix now.

**Comment by BuffaloWill** [comment]
Pushed a quick fix for this issue. I created https://github.com/MooseDojo/Serpico/issues/49 to properly fix the underlying problem. 

Thanks!!
