### ISSUE TITLE
Templated Finding Name Search  

### ISSUE THREAD

**Issue by BuffaloWill** [MooseDojo/Serpico#57]
"As a user I would like to be able to search the finding titles. Using the browser search includes the finding description which is annoying."

The easiest way to do this is with a javascript based search on the template pages only.

**Comment by ccammilleri** [comment]
We've ran into the same issue. Although we like the description preview, we have opt'd to disable it in favor of more effective browser searching. 

e1462258ea792ca1927dd4b4d90ba7ac34140460

**Comment by BuffaloWill** [comment]
@ccammilleri: I hear that

Just pushed the finding title search. It's done with CSS/JS and meant to be light. Like to hear feedback from anyone if this is a good solution or it would be preferred to remove the description preview functionality.
