### ISSUE TITLE
Enchancement: IP address List

### ISSUE THREAD

**Issue by securemaryland** [MooseDojo/Serpico#63]
First let me start by saying thanks for making the product - I just stumbled across it the other day and can already see benefits of using it in the dreaded documentation process. 
I thought it would be nice to include a list of IP addresses/ranges. I was thinking it could be used for summary/scope sections of the document and also in the findings - we could tag which hosts had finding.
Also, I would like to see us be able to add a field to the finding (may already be an option that I haven't seen yet). 

*** added to this to ask a stupid question: how do we factor in formatting into the findings? I see bullets are *- but how do we get italics, headings, etc?

**Comment by BuffaloWill** [comment]
@securemaryland - Hi and thanks for the feedback! Sorry for the slow response.

>
I thought it would be nice to include a list of IP addresses/ranges.
>
This can be done using User Defined Variables. You will want to:
1. Go to Report > Additional Features > Edit User Defined Variables
2. For example, name it "ip_range" and put the range in. Save.
3. Go into your report and add §ip_range§. The ips will be added when the report is generated. 

>
how do we factor in formatting into the findings? I see bullets are *- but how do we get italics, headings, etc?
>
did you figure this out? If you click on the blue "Overview" button on any finding it brings up the notes for the italics, bullets, etc.

Cheers!
