### ISSUE TITLE
Enhancement: Bulk import of vulnerability info from Nessus, etc.

### ISSUE THREAD

**Issue by mcjon3z** [MooseDojo/Serpico#64]
I just came across this project while looking for an alternative to Dradis and must say this is very impressive. I can see this becoming a very useful tool in my playbook.

It appears based upon my limited testing that, in order to import findings from Nessus or Burp the associations must be defined by an ID in an existing vulnerability in the database. In the case of an internal vulnerability assessment this could require the manual creation of hundreds of vulnerability database records before a Nessus report could be successfully imported. It would also mean that Nessus reports would have to be manually cross referenced to identify any new vulnerabilities that may not be present in the Serpico vulnerability database.

Would it be possible to add an option for the Nessus importer to create new vulnerability database entries for vulnerabilities in the .nessus file that do not have a corresponding record already in the Serpico database or perhaps some other means of bulk populating the database and correlating with scanner findings (Nessus DB import, OVAL, CVE)?

**Comment by BuffaloWill** [comment]
@mcjon3z - Sorry for the late reply, took some time off. Thanks for the positive feedback!!

Just pushed a simplified version of this feature. You should now be able to import a nessus xml scan and the findings will be added to the report. From there it should be straightforward to add to the template database.  

To enable:
- In config.json, set nessusmap and auto_import to true

A quick note, sometimes the imported text gets mangled (e.g. importing unsafe characters <, >). To fix just edit through the UI.
