### ISSUE TITLE
Ability to set substitution variable in document footer.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#75]
Hi,

I noticed that the substitution variables do not show or take effect in the footer of the generated pen report. Example. Placing ΩtextΩ͏ in the footer will have no effect.

**Comment by BuffaloWill** [comment]
Hey Rick! The substitution variables only replace in main document component (i.e. word/document.xml). Footer, Headers, and Comments are all stored in different xml files inside of the zip (e.g. footer.xml). 

Currently there is no way to set a substitution variable in the footer. I will change this to a feature request.

**Comment by nanotechz9l** [comment]
Sounds good thanks!

**Comment by BuffaloWill** [comment]
We have decided not to implement this. Thank you for the submission.
