### ISSUE TITLE
White space not being honored after substitution variables.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#76]
Hi I've noticed that the white space in the template is not being honored when the final report is generated.

Template Example:
pen test on ΩAPPLICATION_NAMEΩ application (space)

FINAL report Example:
pen test on ΩAPPLICATION_NAMEΩapplication (no space)

**Comment by BuffaloWill** [comment]
This is verified but need to look into it further. I will update the finding.

**Comment by nanotechz9l** [comment]
Great!

**Comment by BuffaloWill** [comment]
Just pushed a fix for this in https://github.com/MooseDojo/Serpico/commit/4e7bdda6c95699cb3dcad9fc2bbc82fa09052ce3. AFAIK it was a weird subtle bug created by word 2007 vs word 2010 compatibility. The fix has worked in my test cases. @nanotechz9l please test and confirm that this fixes the issue for you.

**Comment by BuffaloWill** [comment]
Had a couple other people confirm this issue. The fix seems to be working. I'll close the bug. Thanks!

**Comment by nanotechz9l** [comment]
Anytime thanks! I'll confirm asap.

**Comment by nanotechz9l** [comment]
Confirmed working, thanks!

**Comment by theguly** [comment]
sorry for reopening this issue, but i have the same problem on a word2016.
how can i help tracing the problem?
