### ISSUE TITLE
Excessive white space in report with multiple findings.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#81]
The Final generated report contains excessive white space between finding sections. Some findings are even copied twice into said sections.

Example:
The remediation section is copied twice into one finding section.

Repro:
The issue is present in the custom template I created by copying a default template. Everything works fine except for the white space and duplicate entries every once in a while. It's likely user (me) error using the meta-language. Let me know if you can take a look thanks!

**Comment by BuffaloWill** [comment]
@nanotechz9l Sure, please e-mail me your template and I can take a look.

**Comment by BuffaloWill** [comment]
Closing for now.
