### ISSUE TITLE
Substitution variable value not being honored throughout generated report.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#82]
I have the same substitution variable placed in various locations in a report template, and once I generate the report the value is only honored in the first substitution variable placeholder instead of all.

Example (Report template):
Page 1.  ΩURLΩ
Page 5.  ΩURLΩ
Page 11.ΩURLΩ

Example (Generated report):
Page 1.   http://dynamism.com
Page 5.   blank
Page 11. blank

**Comment by BuffaloWill** [comment]
@nanotechz9l I haven't seen this issue before. Maybe the substitution variable is misplaced in the second two cases? If you want to e-mail me your template I can take a look.

**Comment by BuffaloWill** [comment]
Closing for now.
