### ISSUE TITLE
cancel button behaves like a submit

### ISSUE THREAD

**Issue by ccammilleri** [MooseDojo/Serpico#83]
I'm guessing this is b/c button's default type is a 'submit' and the type is not defined in a lot of pages.  Perhaps these should be changed to behave similar to view/findings_add.haml:

```
%a{ :href => "/report/#{@report.id}/findings"}
  %input{ :type => "button", :value => 'Cancel'}
```

thoughts?

**Comment by BuffaloWill** [comment]
@ccammilleri you are correct. This should be changed in the other haml files. I'll self-assign this one.
