### ISSUE TITLE
Additional Suggestions for Nessus Import

### ISSUE THREAD

**Issue by mcjon3z** [MooseDojo/Serpico#88]
Great to see the Nessus Import function improvements, particularly the additional information imported in the most recent commit. Thank y'all for the continued work and support for this project!

Couple of additional suggestions:
- ~~Assignment of risk level based on Nessus risk score (currently all imported items come in with a risk level of Low)~~ Issue https://github.com/MooseDojo/Serpico/issues/91 / PR https://github.com/MooseDojo/Serpico/pull/92
- When adding a Nessus report item to the master vulnerability database, could the Nessus ID also be mapped in the new master vulnerability entry at the time it is uploaded?
- Assessment type for all imported vulnerabilities defaults to "External" and have to be changed individually - My personal thought would be that the assessment type would be specific to the engagement, not the individual vulnerabilities, however understandably this may not be consistent with the authors' intent.
- Combining of imported vulnerabilities from multiple runs by plugin ID. Currently, importing 2 Nessus scans with a similar vulnerability will result in 2 separate report items as opposed to combining the results from the second import with the first.
- Support for bulk selection of engagement vulnerabilities for editing, adding to master findings database, and deleting (or ignoring). For example, I personally like to report all patch-related vulnerabilities as a single finding for patch management. This can be based on the "Patch report" Nessus plugin and bulk selection would allow for mass deletion of the individual plugin items for these.
- Related to the previous item, bulk selection and addition of vulnerabilities to a master finding vulnerability (like a singular "Patch management" report item that is linked to many Nessus ID's) or to an "ignore" list so they will not be imported from future scans 
- Also related, support for selecting threshold of vulnerabilities for import - patch report item I mention above is informational and does not get imported; alternatively, some may wish to only import high risk or moderate and high risk findings
- Import of CVSS scoring if CVSS is implemented as discussed in PR 65.

**Comment by BuffaloWill** [comment]
Thanks @mcjon3z for the feedback. Here were my notes. Hopefully the issues are summarized correctly, please update if not =):
* When adding a Nessus report item to the master vulnerability database, could the Nessus ID also be mapped in the new master vulnerability entry at the time it is uploaded? 
-- Issue https://github.com/MooseDojo/Serpico/issues/98

* Assessment type for all imported vulnerabilities defaults to "External" and have to be changed individually - My personal thought would be that the assessment type would be specific to the engagement, not the individual vulnerabilities, however understandably this may not be consistent with the authors' intent.
-- Imported findings should now be set to "Imported" for Nessus and "Web Application" for Burp

* Combining of imported vulnerabilities from multiple runs by plugin ID. Currently, importing 2 Nessus scans with a similar vulnerability will result in 2 separate report items as opposed to combining the results from the second import with the first.
-- Issue https://github.com/MooseDojo/Serpico/issues/99

* Support for bulk selection of engagement vulnerabilities for editing, adding to master findings database, and deleting (or ignoring). For example, I personally like to report all patch-related vulnerabilities as a single finding for patch management. This can be based on the "Patch report" Nessus plugin and bulk selection would allow for mass deletion of the individual plugin items for these.
-- Bulk modification is not something I am comfortable supporting within the UI right now. You should be able to set multiple master ids to one finding of "Patch Management" to solve part of this issue. Also, check out the scripts directory which have examples of bulk finding modification. We could possibly add more scripts for say multiple finding delete for imported items. I've also been considering how to add extension/plugin support such that a script could be run from the UI.

* Related to the previous item, bulk selection and addition of vulnerabilities to a master finding vulnerability (like a singular "Patch management" report item that is linked to many Nessus ID's) or to an "ignore" list so they will not be imported from future scans
-- Similar logic to above.

* Also related, support for selecting threshold of vulnerabilities for import - patch report item I mention above is informational and does not get imported; alternatively, some may wish to only import high risk or moderate and high risk findings
-- Issue https://github.com/MooseDojo/Serpico/issues/100

* Import of CVSS scoring if CVSS is implemented as discussed in PR 65.
-- CVSS will be landed in Q1. I want to do one more round of testing.
