### ISSUE TITLE
Bug in function for adding imported nessus vulnerability to master database?

### ISSUE THREAD

**Issue by mcjon3z** [MooseDojo/Serpico#89]
On my installation, if you attempt to upload a current report finding with a risk rating of "Low" to the master findings database nothing happens. Change it to "Moderate" or higher and it gets added just fine.

**Comment by BuffaloWill** [comment]
@mcjon3z confirmed. The issue was that when importing there was no type applied to the finding. The master database will only display findings that it has a type for. I added a "Imported" type and modified the import to apply this.
