### ISSUE TITLE
Remediation Effort unavailable when creating new finding

### ISSUE THREAD

**Issue by sandoi** [MooseDojo/Serpico#90]
When creating a new finding, you can insert a Title, choose a Finding Type and Vulnerability Risk Level. However, you cannot choose a Remediation Effort. After you save the finding, though, you can choose a Remediation Effort (as well as the Accepted checkbox, but I understand you may not want that when creating a new finding).

**Comment by BuffaloWill** [comment]
thanks @sandoi! just pushed a fix
