### ISSUE TITLE
Vulnerability Import Should Attempt to Assign a Risk Score

### ISSUE THREAD

**Issue by BuffaloWill** [MooseDojo/Serpico#91]
Currently when a vulnerability scan is imported a risk score of low is applied to any finding. Nessus and Burp importers should attempt to apply a risk score inherited from the scan data.

This will require:
1. Identifying where the risk score is stored for a finding in the Nessus and Burp import scans
2. Update vuln_importer.rb to reflect this

**Comment by mcjon3z** [comment]
Actually playing with this as we speak. Got Nessus working...that was easy.
https://github.com/mcjon3z/Serpico/tree/mcjon3z-nessus-fixes

**Comment by BuffaloWill** [comment]
hah. Nice! IMO we need a scoring conversion method; it takes in a risk score and converts to DREAD default and vice versa. So far I've been hard coding and it's error prone. Let me know how your testing goes and I can apply your fix along with the scoring conversion method.

**Comment by mcjon3z** [comment]
Fixing to shoot a PR - feel free to merge or cherry pick

**Comment by BuffaloWill** [comment]
Landed.
