### ISSUE TITLE
Findings view overruns browser window with large notes value from Nessus import

### ISSUE THREAD

**Issue by mcjon3z** [MooseDojo/Serpico#93]
When importing a large credentialed Nessus scan report, the findings page overruns the browser window (see screenshot). This appears to be related to the text imported into the "Notes" field from the "plugin_output" from the nessus XML. If I comment out the line in vuln_importer.rb which brings in the plugin output and then import the same report, the findings view displays properly.

It is unusual because reviewing the source of the findings page shows that that table definition is set to 70% width. Also, there is unbroken text in the description / solution for many of these items that exceeds the page width and they wrap properly so long as there is not a large notes field present.

Nessus report imported with notes:
![serpico_findings_screenshot](https://cloud.githubusercontent.com/assets/6471785/12052650/28a32242-aedf-11e5-8e58-644bd8445398.png)

Nessus report imported without notes:
<img width="1672" alt="serpico_findings_screenshot" src="https://cloud.githubusercontent.com/assets/6471785/12052706/ab064e62-aedf-11e5-92c0-aa864a2efaf6.png">

**Comment by mcjon3z** [comment]
Edit - in troubleshooting this, noticed where the Nessus import feature is incorrectly importing notes data for every plugin run on a particular host since it uses hostnode instead of itemnode. This not only winds up with incorrect plugin data in the notes, but makes them huge and causes this issue with the display.

See https://github.com/MooseDojo/Serpico/issues/94

**Comment by BuffaloWill** [comment]
Ran a handful of tests and seemed to fix the issue.
